import React from "react";
import ReactDOM from "react-dom/client";
import {
  Activity,
  BadgeCheck,
  CircleDollarSign,
  Github,
  RadioTower,
  ShieldCheck,
  Trophy,
  Wallet,
} from "lucide-react";
import "./styles.css";
import "./app-layout.css";

type ProofState = {
  local: string;
  rpc: string;
  xlayer: string;
};

const proof: ProofState = {
  local: "Local/anvil signed proof generated by script",
  rpc: "X Layer testnet RPC smoke checks chain ID 1952",
  xlayer: "Live X Layer write blocked until funded signer is provided",
};

const timeline = [
  { label: "Pick", value: "Argentina over France", status: "fixture-demo" },
  { label: "Sign", value: "Agent wallet signs submitPrediction", status: "real local proof" },
  { label: "Settle", value: "Fixture result resolves as home", status: "fixture-demo" },
  { label: "Score", value: "Accuracy row updates on contract", status: "real local proof" },
];

function App() {
  return (
    <main>
      <nav className="topbar liquid">
        <a className="brand" href="#top" aria-label="Matchday Wallet Agent home">
          Matchday Wallet Agent
        </a>
        <div className="navlinks" aria-label="sections">
          <a href="#proof">Proof</a>
          <a href="#contract">Contract</a>
          <a href="#submit">Submit</a>
        </div>
        <a className="iconButton" href="https://github.com/BonneyMantra" aria-label="Bonney GitHub">
          <Github size={18} />
        </a>
      </nav>

      <section id="top" className="hero">
        <div className="stadiumGlow" />
        <div className="scorebug liquid">
          <span>Fixture/demo data</span>
          <strong>ARG vs FRA</strong>
        </div>
        <div className="heroCopy">
          <p className="eyebrow">X Layer X Cup 2026 / AI Agent Track</p>
          <h1>
            A matchday agent that signs its picks with a wallet.
          </h1>
          <p className="lede">
            The MVP proves a real EVM transaction path: agent pick, wallet signature,
            prediction event, fixture-labeled settlement, and an accuracy row tied to
            the agent address.
          </p>
          <div className="ctaRow">
            <a className="primaryCta" href="#proof">
              <Activity size={18} /> Inspect proof
            </a>
            <a className="secondaryCta" href="#contract">
              <ShieldCheck size={18} /> Contract path
            </a>
          </div>
          <p className="fineprint">
            No live sports oracle, no real-money betting, and no X posting is claimed in
            this run. Seeded data is visibly labeled.
          </p>
        </div>
        <AgentPanel />
      </section>

      <section id="proof" className="proofBand">
        <div className="sectionHeader">
          <p className="eyebrow">Judge-readable state transition</p>
          <h2>Pick → sign → submit → settle → score</h2>
        </div>
        <div className="timeline">
          {timeline.map((item) => (
            <article className="timelineItem liquid" key={item.label}>
              <span>{item.label}</span>
              <strong>{item.value}</strong>
              <small>{item.status}</small>
            </article>
          ))}
        </div>
      </section>

      <section id="contract" className="contractBand">
        <div className="contractCopy">
          <p className="eyebrow">Real integration boundary</p>
          <h2>Live X Layer write is ready, not faked.</h2>
          <p>
            Scripts deploy and submit through X Layer testnet when a funded signer is
            supplied. Until then, the app shows local/anvil transaction proof plus
            read-only X Layer RPC smoke.
          </p>
        </div>
        <div className="proofGrid">
          <ProofCard icon={<Wallet />} label="Local signer" value={proof.local} />
          <ProofCard icon={<RadioTower />} label="X Layer RPC" value={proof.rpc} />
          <ProofCard icon={<CircleDollarSign />} label="Funding blocker" value={proof.xlayer} />
        </div>
      </section>

      <section id="submit" className="submitBand liquid">
        <div>
          <p className="eyebrow">Submission packet</p>
          <h2>Bonney-owned repo and form prep stay reversible.</h2>
          <p>
            Repo creation uses the Bonney browser profile because the local GitHub CLI is
            a different account. The Google Form is preflighted, but final submit and X
            posting require Gabriel approval.
          </p>
        </div>
        <div className="submissionList">
          <span>Repo owner: BonneyMantra</span>
          <span>Form email: 1inchunitedefi@gmail.com</span>
          <span>Needed: funded X Layer signer</span>
        </div>
      </section>
    </main>
  );
}

function AgentPanel() {
  return (
    <aside className="agentPanel liquid" aria-label="Agent wallet status">
      <div className="panelTop">
        <Trophy size={22} />
        <span>Match oracle #01</span>
      </div>
      <div className="agentAddress">
        <span>Agent wallet</span>
        <strong>0x7099...79C8</strong>
      </div>
      <div className="pickBox">
        <span>Current pick</span>
        <strong>Argentina wins</strong>
        <p>Fixture heuristic: home momentum edge. Labeled demo data.</p>
      </div>
      <div className="statusPill">
        <BadgeCheck size={16} />
        Local signing path implemented
      </div>
    </aside>
  );
}

function ProofCard({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <article className="proofCard liquid">
      <div className="proofIcon">{icon}</div>
      <span>{label}</span>
      <strong>{value}</strong>
    </article>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
